# -*- coding: utf-8 -*-

"""
gumletrestapis

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from gumletrestapis.configuration import Configuration, Environment
from gumletrestapis.gumletrestapis_client import GumletrestapisClient
from gumletrestapis.http.auth.custom_header_authentication import CustomHeaderAuthenticationCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = GumletrestapisClient(config=cls.config)

    @staticmethod
    def create_configuration():
        environment = os.getenv('GUMLETRESTAPIS_ENVIRONMENT')
        authorization = os.getenv('GUMLETRESTAPIS_AUTHORIZATION')

        if environment is not None:
            environment = Environment[environment.upper()]
        custom_header_authentication_credentials=None
        if authorization is not None:
            custom_header_authentication_credentials=CustomHeaderAuthenticationCredentials(
                authorization=authorization)


        config = Configuration(http_call_back=HttpResponseCatcher())
        return config.clone_with(
            custom_header_authentication_credentials=custom_header_authentication_credentials,
            environment=environment)

